language: node_js
node_js:
- node
install:
- make install
script:
- make spectral
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: bn5lfI/wK3VTBhWC0VlAysj780tPD0R+EMtrXSvvVvqXv/LbCjUQMwN+yreTE9whURf09NbDlZEc2W1/15R/EBhlfDy0zlpMwkPY7u2UVzNqwjNUpHhyclLK3CnC6fawTZ2RI6WTRS/J35a/u/Yt581ug7nCQPqxfpr54iaxY1/5PYrRgVWSZMqE6uKTVnP+8l4YvEPiFawVXjDwBAECUpt9D6DO36g903d05L8vrQMOJEN3BLaHtOe69yk56vVaLTiBKNVeqcDPDm7VorqVYlbIjXUo7AXTmFqPrXC33hPm8HskXTBhbs1R4Kzm6F9Am3KcrUz/sxR2sWCpdXN0bvTas2YFYA/9pF9W0xFMHwu6t5eqCTI2jKkioZSBzlilk8ZGbz5F3AcReOg3b+utjir8bgUCmBTThjVNEyh0bgdrKsU4YQvfkQXZFAPz2Mg8UaFYS5vdEYA4D0rctQ0lwxlgTcJZAkq72t95CiNbfc70FIwWl++58kkxyXlhZh+FIlGnHgzIRrHg8SXUWLmx/ZnWBm9K/jGmY3sRWLh8fdwMOLuA9uCV+8OQgsRihYLyzhUdlAJDstX0oyxOkTjC1vvCBYa5v/4yfawnuXXKij48P1/j1kcQnKwGzmzQ+X1dIvyw7PfzAF3CVs5iDi+zWGoiew5qGS60HeiVlnGCItI=
